//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public string id_image { get; set; }
        public string name { get; set; }
        public string describe { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> heigth { get; set; }
        public Nullable<int> prority { get; set; }
        public string id_group { get; set; }
        public string url { get; set; }
    
        public virtual GroupImage GroupImage { get; set; }
    }
}
