//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public string id_account { get; set; }
        public string id_role { get; set; }
        public Nullable<double> point { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Account Account { get; set; }
    }
}
