//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string id_orderdetail { get; set; }
        public string id_order { get; set; }
        public string id_product { get; set; }
        public string id_market { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> quanlity { get; set; }
        public Nullable<int> priority { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SMarket SMarket { get; set; }
        public virtual Order Order { get; set; }
    }
}
