//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMarketBrand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMarketBrand()
        {
            this.SMarkets = new HashSet<SMarket>();
        }
    
        public string id_brand { get; set; }
        public string name { get; set; }
        public string id_group_image { get; set; }
    
        public virtual GroupImage GroupImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMarket> SMarkets { get; set; }
    }
}
