//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMarket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMarket()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ProductInMarkets = new HashSet<ProductInMarket>();
        }
    
        public string id_market { get; set; }
        public string name { get; set; }
        public string id_group_address { get; set; }
        public string id_brand { get; set; }
        public string id_image_group { get; set; }
    
        public virtual GroupAddress GroupAddress { get; set; }
        public virtual GroupImage GroupImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInMarket> ProductInMarkets { get; set; }
        public virtual SMarketBrand SMarketBrand { get; set; }
    }
}
