//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfig
    {
        public string id { get; set; }
        public string password_secret_key { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string USER_ROLE { get; set; }
        public string ORDER_STATE { get; set; }
        public string LEVEL_USER { get; set; }
        public string PRODUCT_TYPE { get; set; }
    }
}
