//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string id_transaction { get; set; }
        public string id_order { get; set; }
        public Nullable<double> money { get; set; }
        public Nullable<System.DateTime> created_time { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
